(() => {
  'use strict';
  const config=window.ODYSSEY_PORTAL_CONFIG,homePath=config?.homePath||'portal.html';
  const ROUTES={athlete:[['Home',homePath],['Training','portal-training.html'],['Messages','portal-messages.html'],['Schedule','portal-schedule.html'],['Progress','portal-progress.html']],coach:[['Home','coach-portal.html'],['Attendance','coach-attendance.html'],['Messages','coach-messages.html'],['Assignments','coach-assignments.html'],['Review','coach-review.html']],guardian:[['Account','guardian-portal.html']]};
  const PAGES={'portal.html':['athlete','Home'],'portal-training.html':['athlete','Training'],'portal-messages.html':['athlete','Messages'],'portal-schedule.html':['athlete','Schedule'],'portal-progress.html':['athlete','Progress'],'coach-portal.html':['coach','Home'],'coach-attendance.html':['coach','Attendance'],'coach-messages.html':['coach','Messages'],'coach-assignments.html':['coach','Assignments'],'coach-review.html':['coach','Review'],'guardian-portal.html':['guardian','Account']};
  const file=location.pathname.split('/').pop()||homePath,requested=PAGES[file]||PAGES[homePath]||PAGES['portal.html'];
  const requestedAccountFlow=new URLSearchParams(location.search).get('account');
  const callbackType=new URLSearchParams(location.hash.slice(1)).get('type');
  const accountFlow=['invite','recovery'].includes(requestedAccountFlow)?requestedAccountFlow:(['invite','recovery'].includes(callbackType)?callbackType:null);
  const auth=document.querySelector('#portal-auth'),authForm=document.querySelector('#portal-auth-form'),app=document.querySelector('#portal-app'),content=document.querySelector('#portal-page-content'),nav=document.querySelector('#portal-page-nav'),status=document.querySelector('#app-status');
  auth.hidden=true;
  let adapter,client,passwordFlow=accountFlow==='recovery'||accountFlow==='invite';
  const e=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n};
  const panel=(k,t,wide=false)=>{const n=e('section',`portal-panel${wide?' wide':''}`);n.append(e('p','kicker',k),e('h2','',t));return n};
  const record=(t,m)=>{const n=e('article','portal-record');n.append(e('strong','',t),e('span','',m));return n};
  const fmt=(v,time=false)=>v?new Intl.DateTimeFormat('en-US',time?{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}:{weekday:'short',month:'short',day:'numeric'}).format(new Date(v)):'Date unavailable';
  const metricLabels={acceleration_10m:'10m acceleration',acceleration_20m:'20m acceleration',flying_20m:'Flying 20m',sprint_60m:'60m sprint',sprint_100m:'100m sprint',standing_broad_jump:'Standing broad jump'};
  const unitLabels={s:'seconds',sec:'seconds',seconds:'seconds',m:'meters',cm:'centimeters'};
  const statusLabels={draft:'Draft',published:'Published',completed:'Completed',canceled:'Canceled'};
  const metricName=value=>metricLabels[String(value||'').toLowerCase()]||'Performance result';
  const unitName=value=>unitLabels[String(value||'').toLowerCase()]||'';
  const statusName=value=>statusLabels[String(value||'').toLowerCase()]||'Training plan';
  const url=f=>f;
  const fail=()=>{status.textContent='We could not complete that action. Please try again.'};
  const setFormBusy=(form,busy)=>{form.setAttribute('aria-busy',String(busy));form.querySelectorAll('button,input,select,textarea').forEach(control=>control.disabled=busy)};
  const buildAdapter=()=>{if(!config?.supabaseUrl||!config?.supabasePublishableKey||!window.supabase?.createClient||typeof window.createOdysseyPortalAdapter!=='function')return null;client=window.supabase.createClient(config.supabaseUrl,config.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});client.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY'){passwordFlow=true;queueMicrotask(()=>showPasswordForm())}});return window.createOdysseyPortalAdapter({client})};
  const singleRole=roles=>Array.isArray(roles)&&roles.length===1?roles[0]:null;
  const enforce=role=>{if(requested[0]===role)return true;location.replace(url(ROUTES[role]?.[0]?.[1]||'portal.html'));return false};
  const heading=(role,page)=>{const names={athlete:{Home:'Athlete home',Training:'Training',Messages:'Contact coach',Schedule:'Schedule',Progress:'Progress'},coach:{Home:'Coach home',Attendance:'Attendance',Messages:'Athlete messages',Assignments:'Assignments',Review:'Review'},guardian:{Account:'Account'}};document.querySelector('#portal-role-label').textContent=role==='guardian'?'Parent / guardian':role;document.querySelector('#portal-page-title').textContent=names[role][page];document.querySelector('#portal-page-intro').textContent=role==='athlete'?'Own the work. Stay connected. Track what comes next.':role==='coach'?'Guide the work with clarity and consistency.':'Manage consent and account information.';document.title=`${names[role][page]} | The Board`};
  const buildNav=role=>nav.replaceChildren(...ROUTES[role].map(([label,target])=>{const a=e('a','',label);a.href=url(target);if(target===file)a.setAttribute('aria-current','page');return a}));
  const authForms=e('div','portal-auth-forms'),forgotButton=e('button','portal-auth-link','Forgot password?'),resetForm=e('form','portal-form'),passwordForm=e('form','portal-form');
  authForm.before(authForms);authForms.append(authForm,resetForm,passwordForm);forgotButton.type='button';authForm.insertBefore(forgotButton,authForm.querySelector('.form-message'));
  resetForm.hidden=true;resetForm.innerHTML='<h2>Reset your password</h2><p class="portal-muted">Enter your account email and we will send a secure reset link.</p><label>Email<input name="email" type="email" autocomplete="email" required></label><button class="button primary" type="submit">Send reset link</button><button class="portal-auth-link" type="button" data-auth-back>Back to sign in</button><p class="form-message" role="status"></p>';
  passwordForm.hidden=true;passwordForm.innerHTML=`<h2>${accountFlow==='invite'?'Create your password':'Choose a new password'}</h2><p class="portal-muted">Use at least eight characters.</p><label>New password<input name="password" type="password" minlength="8" autocomplete="new-password" required></label><label>Confirm new password<input name="confirm_password" type="password" minlength="8" autocomplete="new-password" required></label><button class="button primary" type="submit">Save password</button><p class="form-message" role="status"></p>`;
  if(config?.showBetaNotice){const notice=e('aside','portal-beta-notice'),label=e('strong','','Invited preview'),copy=e('p','','This preview uses sample accounts and sample training information. Nothing here changes an Odyssey member account.');notice.setAttribute('aria-label','Invited preview');notice.append(label,copy);auth.before(notice)}
  const showAuthForm=form=>{auth.hidden=false;app.hidden=true;[authForm,resetForm,passwordForm].forEach(item=>item.hidden=item!==form)};
  const showPasswordForm=()=>{showAuthForm(passwordForm);passwordForm.querySelector('input')?.focus()};
  const recoveryUrl=()=>{const target=new URL(homePath,location.href);target.search='';target.hash='';target.searchParams.set('account','recovery');return target.href};
  forgotButton.addEventListener('click',()=>{showAuthForm(resetForm);resetForm.querySelector('input')?.focus()});resetForm.querySelector('[data-auth-back]').addEventListener('click',()=>{showAuthForm(authForm);authForm.querySelector('input')?.focus()});
  resetForm.addEventListener('submit',async ev=>{ev.preventDefault();const msg=resetForm.querySelector('.form-message');msg.textContent='';if(!resetForm.reportValidity())return;try{await adapter.requestPasswordReset({email:new FormData(resetForm).get('email'),redirectTo:recoveryUrl()});resetForm.reset();msg.textContent='If that email belongs to an invited account, a reset link is on the way.'}catch{msg.textContent='We could not send a reset link right now. Please try again.'}});
  passwordForm.addEventListener('submit',async ev=>{ev.preventDefault();const msg=passwordForm.querySelector('.form-message'),values=Object.fromEntries(new FormData(passwordForm));msg.textContent='';if(!passwordForm.reportValidity())return;if(values.password!==values.confirm_password){msg.textContent='The passwords do not match.';return}try{await adapter.updatePassword({password:values.password})}catch{msg.textContent='We could not save your password. Request a new link and try again.';return}passwordFlow=false;history.replaceState({},'',homePath);try{const result=await adapter.initialize();if(result.signedIn)await signedIn(result.user,result.roles);else{showAuthForm(authForm);authForm.querySelector('.form-message').textContent='Your password was saved. Sign in to continue.'}}catch{showAuthForm(authForm);authForm.querySelector('.form-message').textContent='Your password was saved. Please contact Odyssey to confirm your access to The Board.'}});
  const renderAthleteHome=data=>{const grid=e('div','portal-grid'),work=panel('Today','Upcoming training',true),messages=panel('Coach connection','Latest message'),schedule=panel('Next session','Schedule');if(data.plans.length)data.plans.slice(0,2).forEach(({training_plans:p})=>work.append(record(p.title,`${fmt(p.planned_date)} · Week ${p.training_week}`)));else work.append(e('p','portal-muted','No published training has been assigned yet.'));const latest=data.messages[0];messages.append(latest?record(latest.body,fmt(latest.created_at,true)):e('p','portal-muted','No messages yet.'));const next=data.sessions[0];schedule.append(next?record(next.title,`${fmt(next.starts_at,true)} · ${next.location}`):e('p','portal-muted','No open sessions right now.'));grid.append(work,messages,schedule);content.replaceChildren(grid)};
  const renderTraining=data=>{const grid=e('div','portal-grid'),work=panel('Assigned by your coach','Upcoming work',true);if(!data.plans.length)work.append(e('p','portal-muted','No published training has been assigned yet.'));data.plans.forEach(({plan_id:id,training_plans:p})=>{const card=record(p.title,`${fmt(p.planned_date)} · Week ${p.training_week}`),blocks=e('div','portal-list');(p.training_plan_sections||[]).sort((a,b)=>a.sort_order-b.sort_order).forEach(s=>{const d=document.createElement('details'),sum=document.createElement('summary'),ul=e('ul','portal-list');sum.textContent=s.heading;(s.training_plan_items||[]).sort((a,b)=>a.sort_order-b.sort_order).forEach(i=>ul.append(e('li','',[i.exercise,i.sets&&`${i.sets} sets`,i.reps,i.intensity].filter(Boolean).join(' · '))));d.append(sum,ul);blocks.append(d)});card.append(blocks);const form=e('form','portal-form');form.innerHTML='<div class="portal-form-row"><label>Workout status<select name="completion_status" required><option value="">Choose status</option><option value="completed">Completed</option><option value="partial">Partially completed</option><option value="missed">Missed</option></select></label><label>Effort (1–10)<input name="effort" type="number" min="1" max="10"></label></div><label>Note for your coach<textarea name="note" rows="3" maxlength="2000"></textarea></label><div class="portal-actions"><button class="button primary" type="submit">Save check-in</button></div><p class="form-message" role="status"></p>';form.addEventListener('submit',async ev=>{ev.preventDefault();if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));setFormBusy(form,true);try{await adapter.saveCheckIn({planId:id,...values});form.querySelector('.form-message').textContent='Check-in saved.'}catch{form.querySelector('.form-message').textContent='We could not save your check-in. Please try again.'}finally{setFormBusy(form,false)}});card.append(form);work.append(card)});grid.append(work);content.replaceChildren(grid)};
  const appendMessage=(history,message,isYou=false)=>{const bubble=e('article',`portal-message${isYou?' is-you':''}`);bubble.append(e('p','',message.body),e('small','',fmt(message.created_at,true)));history.append(bubble)};
  const bindEnterToSend=(textarea,form)=>textarea.addEventListener('keydown',ev=>{if(ev.key!=='Enter'||ev.shiftKey||ev.isComposing||ev.keyCode===229)return;ev.preventDefault();if(textarea.value.trim())form.requestSubmit();else form.querySelector('.form-message').textContent='Enter a message before sending.'});
  const renderAthleteMessages=data=>{const shell=e('section','portal-chat'),coach=data.assignedCoach?.displayName||'Your assigned coach',head=e('header','portal-panel'),history=e('div','portal-chat-history');head.append(e('p','kicker','Contact coach'),e('h2','',coach));history.setAttribute('aria-label',`Conversation with ${coach}`);if(!data.messages.length)history.append(e('p','portal-muted','No messages yet.'));[...data.messages].reverse().forEach(m=>appendMessage(history,m,m.sender_user_id===data.userId));const form=e('form','portal-chat-form');form.innerHTML=`<label for="chat-message">Message coach</label><textarea id="chat-message" name="body" maxlength="4000" required placeholder="Message coach…"></textarea><button class="button primary" type="submit">Send</button><p class="form-message" role="status"></p>`;const textarea=form.querySelector('textarea');form.querySelector('label').textContent=`Message ${coach}`;textarea.placeholder=`Message ${coach}…`;bindEnterToSend(textarea,form);form.addEventListener('submit',async ev=>{ev.preventDefault();const body=String(new FormData(form).get('body')||'').trim();if(!body){form.querySelector('.form-message').textContent='Enter a message before sending.';return}if(!form.reportValidity())return;setFormBusy(form,true);try{const sent=await adapter.sendMessage({body});appendMessage(history,{...sent,body,created_at:sent?.created_at||new Date().toISOString()},true);form.reset();form.querySelector('.form-message').textContent='Message sent.';history.scrollTop=history.scrollHeight}catch{form.querySelector('.form-message').textContent='We could not send your message. Please try again.'}finally{setFormBusy(form,false)}});shell.append(head,history,form);content.replaceChildren(shell);adapter.markMessagesRead({}).catch(()=>{});requestAnimationFrame(()=>history.scrollTop=history.scrollHeight)};
  const renderCoachMessages=data=>{
    const shell=e('section','portal-grid'),list=e('nav','portal-panel'),thread=e('section','portal-panel'),threads=data.messageThreads||[],buttons=new Map();
    list.setAttribute('aria-label','Athlete conversations');list.append(e('p','kicker','Messages'),e('h2','','Athletes'));
    const renderThread=athlete=>{
      const messages=athlete.messages||[],history=e('div','portal-chat-history'),form=e('form','portal-chat-form');
      thread.replaceChildren(e('p','kicker','Conversation'),e('h2','',athlete.displayName));history.setAttribute('aria-label',`Conversation with ${athlete.displayName}`);
      if(!messages.length)history.append(e('p','portal-muted','No messages with this athlete yet.'));messages.forEach(m=>appendMessage(history,m,m.sender_user_id===data.userId));
      form.innerHTML='<label for="coach-chat-message">Message athlete</label><textarea id="coach-chat-message" name="body" maxlength="4000" required placeholder="Write a message…"></textarea><button class="button primary" type="submit">Send</button><p class="form-message" role="status"></p>';
      const textarea=form.querySelector('textarea');bindEnterToSend(textarea,form);
      form.addEventListener('submit',async ev=>{ev.preventDefault();const msg=form.querySelector('.form-message'),body=String(new FormData(form).get('body')||'').trim();if(!body){msg.textContent='Enter a message before sending.';return}if(!form.reportValidity())return;setFormBusy(form,true);try{const sent=await adapter.sendMessage({athleteId:athlete.athleteId,body});const message={...sent,body,created_at:sent?.created_at||new Date().toISOString(),sender_user_id:data.userId};messages.push(message);appendMessage(history,message,true);form.reset();msg.textContent='Message sent.';history.scrollTop=history.scrollHeight}catch{msg.textContent='We could not send your message. Please try again.'}finally{setFormBusy(form,false)}});
      thread.append(history,form);list.querySelectorAll('button').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.athleteId===athlete.athleteId)));
      adapter.markMessagesRead({athleteId:athlete.athleteId}).then(()=>{athlete.unreadCount=0;const button=buttons.get(athlete.athleteId);if(button)button.textContent=`${athlete.displayName} · 0 unread`}).catch(()=>{});
      requestAnimationFrame(()=>history.scrollTop=history.scrollHeight);
    };
    threads.forEach(athlete=>{const button=e('button','button secondary',`${athlete.displayName} · ${athlete.unreadCount} unread`);button.type='button';button.dataset.athleteId=athlete.athleteId;button.addEventListener('click',()=>renderThread(athlete));buttons.set(athlete.athleteId,button);list.append(button)});
    if(!threads.length){list.append(e('p','portal-muted','No assigned athletes.'));thread.append(e('p','portal-muted','No conversations are available.'))}shell.append(list,thread);content.replaceChildren(shell);if(threads.length)renderThread(threads.find(a=>a.athleteId===data.athleteId)||threads[0]);
  };
  const renderSchedule=data=>{
    const grid=e('div','portal-grid'),enabled=config?.enableSessionReservations===true,p=panel('Training schedule',enabled?'Reserve your training time':'Upcoming sessions',true),reserved=new Set(data.reservations.map(r=>r.session_id));
    if(!enabled)p.append(e('p','portal-muted','Online reservations are not available yet. Contact your coach to confirm your training days.'));
    if(!data.sessions.length)p.append(e('p','portal-muted','No upcoming sessions are currently listed.'));
    data.sessions.forEach(s=>{
      const card=record(s.title,`${fmt(s.starts_at,true)} · ${s.location}`);
      if(enabled){const button=e('button','button secondary',reserved.has(s.id)?'Cancel reservation':'Reserve session');button.type='button';button.disabled=!reserved.has(s.id)&&s.reservation_status!=='open';button.addEventListener('click',async()=>{const reserve=button.textContent==='Reserve session';button.disabled=true;try{await adapter.reserveSession({sessionId:s.id,reserve});button.textContent=reserve?'Cancel reservation':'Reserve session'}catch{fail()}finally{button.disabled=button.textContent==='Reserve session'&&s.reservation_status!=='open'}});card.append(button)}
      p.append(card);
    });grid.append(p);content.replaceChildren(grid);
  };
  const renderProgress=data=>{const grid=e('div','portal-grid'),p=panel('Progress','Performance history',true);if(!data.performance.length)p.append(e('p','portal-muted','No approved results yet.'));data.performance.forEach(r=>{const name=r.performance_metric_definitions?.display_name||metricName(r.metric_code),unit=unitName(r.performance_metric_definitions?.unit);p.append(record(name,`${r.result_value}${unit?` ${unit}`:''} · ${fmt(r.measured_at)}`))});grid.append(p);content.replaceChildren(grid)};
  const renderCoachHome=data=>{const grid=e('div','portal-grid'),athletes=panel('Your roster','Assigned athletes',true),inbox=panel('Messages','Unread'),review=panel('Results','Awaiting review');data.athletes.forEach(a=>athletes.append(record(a.displayName,'Active athlete')));inbox.append(e('strong','',String(data.inbox.length)));review.append(e('strong','',String(data.pendingResults.length)));grid.append(athletes,inbox,review);content.replaceChildren(grid)};
  const addOptions=(select,items,valueKey,label)=>items.forEach(item=>{const option=e('option','',label(item));option.value=item[valueKey];select.append(option)});
  const renderCoachAttendance=(data,p)=>{
    data.sessions.forEach(session=>p.append(record(session.title,`${fmt(session.starts_at,true)} · ${session.location}`)));if(!data.sessions.length)p.append(e('p','portal-muted','No upcoming sessions.'));
    if(!data.sessions.length||!data.athletes.length)return;
    const form=e('form','portal-form');form.innerHTML='<h3>Record attendance</h3><div class="portal-form-row"><label>Session<select name="sessionId" required><option value="">Choose a session</option></select></label><label>Athlete<select name="athleteId" required><option value="">Choose an athlete</option></select></label></div><div class="portal-form-row"><label>Status<select name="status" required><option value="present">Present</option><option value="late">Late</option><option value="excused">Excused</option><option value="absent">Absent</option></select></label><label>Note<textarea name="note" rows="2" maxlength="1000"></textarea></label></div><div class="portal-actions"><button class="button primary" type="submit">Save attendance</button></div><p class="form-message" role="status"></p>';
    addOptions(form.elements.sessionId,data.sessions,'id',session=>`${session.title} · ${fmt(session.starts_at,true)}`);addOptions(form.elements.athleteId,data.athletes,'athleteId',athlete=>athlete.displayName);
    form.addEventListener('submit',async ev=>{ev.preventDefault();const msg=form.querySelector('.form-message');msg.textContent='';if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));setFormBusy(form,true);try{await adapter.saveAttendance(values);msg.textContent='Attendance saved.'}catch{msg.textContent='We could not save attendance. Please try again.'}finally{setFormBusy(form,false)}});p.append(form);
  };
  const renderCoachAssignments=(data,p)=>{
    const list=e('div','portal-list');
    const appendPlan=(plan,atStart=false)=>{const card=record(plan.title,`${fmt(plan.planned_date)} · ${statusName(plan.status)}`);if(plan.status==='draft'){const actions=e('div','portal-actions'),publish=e('button','button secondary','Publish');publish.type='button';publish.addEventListener('click',async()=>{publish.disabled=true;try{await adapter.publishWorkout({planId:plan.id});plan.status='published';card.querySelector('span').textContent=`${fmt(plan.planned_date)} · Published`;publish.remove()}catch{publish.disabled=false;status.textContent='We could not publish that workout. Please try again.'}});actions.append(publish);card.append(actions)}list[atStart?'prepend':'append'](card)};
    data.plans.forEach(plan=>appendPlan(plan));if(!data.plans.length)list.append(e('p','portal-muted','No training plans yet.'));p.append(list);
    if(!data.athletes.length){p.append(e('p','portal-muted','An assigned athlete is required before creating a workout.'));return}
    const form=e('form','portal-form');form.innerHTML='<h3>Create a workout draft</h3><div class="portal-form-row"><label>Athlete<select name="targetAthleteId" required><option value="">Choose an athlete</option></select></label><label>Workout date<input name="plannedDate" type="date" required></label></div><div class="portal-form-row"><label>Title<input name="title" maxlength="160" required></label><label>Training week<input name="trainingWeek" type="number" min="1" max="53" required></label></div><label>Training phase<input name="phase" maxlength="80" placeholder="Preparation" required></label><div class="portal-form-row"><label>Section heading<input name="heading" maxlength="120" placeholder="Main work" required></label><label>Exercise<input name="exercise" maxlength="160" required></label></div><div class="portal-form-row"><label>Sets<input name="sets" type="number" min="1" max="99"></label><label>Reps or distance<input name="reps" maxlength="80" placeholder="3 × 20m"></label></div><label>Rest between sets (seconds)<input name="restSeconds" type="number" min="0" max="3600"></label><div class="portal-actions"><button class="button primary" type="submit">Save draft</button></div><p class="form-message" role="status"></p>';
    addOptions(form.elements.targetAthleteId,data.athletes,'athleteId',athlete=>athlete.displayName);
    form.addEventListener('submit',async ev=>{ev.preventDefault();const msg=form.querySelector('.form-message'),values=Object.fromEntries(new FormData(form));msg.textContent='';if(!form.reportValidity())return;const item={exercise:values.exercise,reps:values.reps||null};if(values.sets)item.sets=Number(values.sets);if(values.restSeconds)item.rest_seconds=Number(values.restSeconds);setFormBusy(form,true);try{const created=await adapter.createWorkout({title:values.title,plannedDate:values.plannedDate,trainingWeek:Number(values.trainingWeek),phase:values.phase,targetAthleteId:values.targetAthleteId,sections:[{section_type:'main',heading:values.heading,items:[item]}]});appendPlan({...created,title:values.title,planned_date:values.plannedDate},true);form.reset();msg.textContent='Draft saved. Review it above when you are ready to publish.'}catch{msg.textContent='We could not save that workout. Check the details and try again.'}finally{setFormBusy(form,false)}});p.append(form);
  };
  const renderCoachPage=(data,page)=>{const grid=e('div','portal-grid'),p=panel(page==='Attendance'?'Session check-in':page==='Assignments'?'Training plans':'Athlete submissions',page,true);if(page==='Attendance')renderCoachAttendance(data,p);else if(page==='Assignments')renderCoachAssignments(data,p);else{data.pendingResults.forEach(r=>{const card=record(metricName(r.metric_code),`${r.result_value} · ${fmt(r.measured_at)}`),actions=e('div','portal-actions');[['Approve','approve'],['Return','reject']].forEach(([label,action])=>{const b=e('button',`button ${action==='approve'?'primary':'secondary'}`,label);b.type='button';b.addEventListener('click',async()=>{try{await adapter.reviewSubmission({resultId:r.id,action});card.remove()}catch{fail()}});actions.append(b)});card.append(actions);p.append(card)});if(!data.pendingResults.length)p.append(e('p','portal-muted','Nothing is waiting for review.'))}grid.append(p);content.replaceChildren(grid)};
  const renderGuardian=data=>{const grid=e('div','portal-grid'),p=panel('Account access','Consent relationships',true);p.append(e('p','portal-muted',`${data.consentRelationships.length} active relationship${data.consentRelationships.length===1?'':'s'}.`));grid.append(p);content.replaceChildren(grid)};
  const render=(role,page,data)=>{heading(role,page);buildNav(role);if(role==='athlete'){if(page==='Home')renderAthleteHome(data);else if(page==='Training')renderTraining(data);else if(page==='Messages')renderAthleteMessages(data);else if(page==='Schedule')renderSchedule(data);else renderProgress(data)}else if(role==='coach'){if(page==='Home')renderCoachHome(data);else if(page==='Messages')renderCoachMessages(data);else renderCoachPage(data,page)}else renderGuardian(data)};
  const signedOut=()=>showAuthForm(authForm);
  const signedIn=async(user,roles)=>{const role=singleRole(roles);if(!role){signedOut();authForm.querySelector('.form-message').textContent='Please contact Odyssey to confirm your access to The Board.';return}if(!enforce(role))return;await adapter.authorizeRoute({requiredRole:requested[0]});const data=await adapter.loadRole({role});render(role,requested[1],data);document.querySelector('#portal-account-email').textContent=user?.email||'';auth.hidden=true;app.hidden=false};
  const signOut=async()=>{try{await adapter.signOut()}finally{location.replace(url(homePath))}};document.querySelector('#portal-sign-out')?.addEventListener('click',signOut);document.querySelector('#portal-app-sign-out')?.addEventListener('click',signOut);
  authForm.addEventListener('submit',async ev=>{ev.preventDefault();const msg=authForm.querySelector('.form-message');msg.textContent='';if(!authForm.reportValidity())return;try{const result=await adapter.signIn(Object.fromEntries(new FormData(authForm)));await signedIn(result.user,result.roles)}catch{msg.textContent='We could not sign you in. Check your email and password, then try again.'}});
  (async()=>{adapter=buildAdapter();if(!adapter){signedOut();authForm.querySelector('.form-message').textContent='The Board is temporarily unavailable.';return}try{const result=await adapter.initialize({resolveAccess:!passwordFlow});if(passwordFlow){if(result.signedIn)showPasswordForm();else{signedOut();authForm.querySelector('.form-message').textContent='This account link is no longer valid. Request a new password link to continue.'}}else if(result.signedIn)await signedIn(result.user,result.roles);else signedOut()}catch{signedOut();authForm.querySelector('.form-message').textContent='The Board is temporarily unavailable. Please try again shortly.'}})();
})();
