-- Odyssey portal database setup. Run once in the Supabase SQL Editor.

create table if not exists public.athlete_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '', age_group text, primary_event text, goals text,
  updated_at timestamptz not null default now()
);
create table if not exists public.coaches (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
create or replace function public.is_coach() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.coaches where user_id = (select auth.uid()));
$$;
revoke all on function public.is_coach() from public;
grant execute on function public.is_coach() to authenticated;

create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  athlete_id uuid not null references public.athlete_profiles(id) on delete cascade,
  coach_id uuid not null references auth.users(id), workout_date date not null,
  title text not null check (char_length(title) between 1 and 120),
  details text not null check (char_length(details) between 1 and 5000),
  created_at timestamptz not null default now()
);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  athlete_id uuid not null references public.athlete_profiles(id) on delete cascade,
  sender_id uuid not null references auth.users(id),
  body text check (body is null or char_length(body) between 1 and 4000),
  attachment_path text, attachment_name text, attachment_type text,
  created_at timestamptz not null default now(),
  constraint message_has_content check (body is not null or attachment_path is not null)
);
create index if not exists workouts_athlete_date_idx on public.workouts (athlete_id, workout_date desc);
create index if not exists messages_athlete_created_idx on public.messages (athlete_id, created_at);

alter table public.athlete_profiles enable row level security;
alter table public.coaches enable row level security;
alter table public.workouts enable row level security;
alter table public.messages enable row level security;

drop policy if exists "Athletes read own profile and coaches read all" on public.athlete_profiles;
create policy "Athletes read own profile and coaches read all" on public.athlete_profiles
for select to authenticated using ((select auth.uid()) = id or (select public.is_coach()));
drop policy if exists "Athletes create own profile" on public.athlete_profiles;
create policy "Athletes create own profile" on public.athlete_profiles
for insert to authenticated with check ((select auth.uid()) = id and not (select public.is_coach()));
drop policy if exists "Athletes update own profile" on public.athlete_profiles;
create policy "Athletes update own profile" on public.athlete_profiles
for update to authenticated using ((select auth.uid()) = id and not (select public.is_coach()))
with check ((select auth.uid()) = id and not (select public.is_coach()));

drop policy if exists "Portal members read workouts" on public.workouts;
create policy "Portal members read workouts" on public.workouts
for select to authenticated using ((select auth.uid()) = athlete_id or (select public.is_coach()));
drop policy if exists "Coaches assign workouts" on public.workouts;
create policy "Coaches assign workouts" on public.workouts
for insert to authenticated with check ((select public.is_coach()) and (select auth.uid()) = coach_id);

drop policy if exists "Portal members read conversation" on public.messages;
create policy "Portal members read conversation" on public.messages
for select to authenticated using ((select auth.uid()) = athlete_id or (select public.is_coach()));
drop policy if exists "Portal members send messages" on public.messages;
create policy "Portal members send messages" on public.messages
for insert to authenticated with check (
  (select auth.uid()) = sender_id and ((select auth.uid()) = athlete_id or (select public.is_coach()))
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('portal-files', 'portal-files', false, 20971520,
  array['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/quicktime'])
on conflict (id) do update set public = excluded.public,
  file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
drop policy if exists "Portal members read athlete files" on storage.objects;
create policy "Portal members read athlete files" on storage.objects for select to authenticated
using (bucket_id = 'portal-files' and ((storage.foldername(name))[1] = (select auth.uid())::text or (select public.is_coach())));
drop policy if exists "Portal members upload athlete files" on storage.objects;
create policy "Portal members upload athlete files" on storage.objects for insert to authenticated
with check (bucket_id = 'portal-files' and ((storage.foldername(name))[1] = (select auth.uid())::text or (select public.is_coach())));

-- The coach must already exist in Authentication > Users before this statement is run.
insert into public.coaches (user_id)
select id from auth.users where email = 'odysseytrackclub@gmail.com'
on conflict (user_id) do nothing;
